### ISSUE TITLE
Swift 3.0

### ISSUE THREAD

**Issue by DaveWoodCom** [DaveWoodCom/XCGLogger#143]
___Starting a separate issue to track issues with the Swift 3.0 branch___

Ok, it's not quite where I want it yet, still some more to add/fix, but I've pushed up where I'm at so far. There are a tonne of changes, and I haven't updated the docs yet. You'll want to look at the demo apps to see how to use it now. Lots of new features, log formatting (ANSI colours etc), log filtering (exclude logs from specific files), easier to add/customize log destinations, and a tonne of renaming to adjust to the new Swift 3 way of doing things.

Still planned for the short term (late tonight/tomorrow):
- Add demo's for filtering (including additional example filters)
- Add Objective-C exception handling to fix #123
- Documentation/Readme updates
- More probably.

Please give me any feedback, issues that you see with this new version, bugs obviously, but I'm also interested in how you think the architecture is changing. Ie, multiple files, destination updates, how filtering/formatting is applied etc.

This will likely be the last commit that will be 'pure swift' since I need to incorporate Objective-C to handle the exceptions that Swift can't catch. I doubt that's a problem for anyone, but if it is, please let me know.

**Comment by gmckenzi** [comment]
FYI - Basic usage (just console logging, no file logging yet) of XCGLogger in my Swift 3 project is working great.

**Comment by DaveWoodCom** [comment]
Think the swift_3.0 branch should be in decent shape and ready for production. If no issues or problems arise, I'll make version 4.0.0 final and move it to master.

**Comment by thatjuan** [comment]
I'm having an issue trying to use the swift_3.0 branch with Cocoapods. I have added the following to my Podfile:

`pod 'XCGLogger', :git => 'https://github.com/DaveWoodCom/XCGLogger.git', :branch => ‘swift_3.0’`

After a `pod install`, XCode is still asking to set `SWIFT_VERSION` to legacy for the XCGLogger Pod. Am I missing a step?

p.s. I also tried removing my pods cache and then re-installing from scratch with `pod install`

**Comment by brightsider** [comment]
When you release 4.0.0?

**Comment by DaveWoodCom** [comment]
@thatjuan Check your cocoapods version `pod --version`. You need to be running the latest (as of yet unreleased version) `1.1.0.rc.2`. You should be able to update to it by entering `sudo gem update cocoapods --pre` and then update your project with `pod update`. The error you're seeing should disappear at this point.

Also, check your podfile, you have smart quotes in there: `‘swift_3.0’` vs `'swift_3.0'`. CocoaPods will still work, but it'll give you a warning, which will get to be annoying.

**Comment by DaveWoodCom** [comment]
@brightsider Hope to release it very soon. It should be completely usable at this point. I'm just testing a few things internally still.

Also, I'd really love to hear some feedback on this new feature: https://github.com/DaveWoodCom/XCGLogger/tree/swift_3.0#filtering-log-messages and especially the options related to it here: https://github.com/DaveWoodCom/XCGLogger/tree/swift_3.0#mixing-and-matching

💬   Anyone ❓❓❓

**Comment by brightsider** [comment]
@DaveWoodCom I'm can't use, because I need it for own podspec and podspec don't allows to use a branch or git path :(

**Comment by DaveWoodCom** [comment]
@brightsider Ok. Well if I don't hear of any other issues by the end of the day, I'll be making the Swift 3.0 branch master.

**Comment by xyzisinus** [comment]
Thanks for the timely hard work.

**Comment by kevinlee85** [comment]
let log = XCGLogger.defaultInstance() 
Type 'XCGLogger' has no member of defaultInstance

**Comment by kevinlee85** [comment]
Sorry. I have read your Swift3.0 readme. I should use let log = XCGLogger.default

**Comment by DaveWoodCom** [comment]
Beta 5 pushed. Rejigged tagging, and have added subspecs to CocoaPods. If nothing blows up with these changes, I'll make 4.0.0 official today...

**Comment by neilt** [comment]
I get the following two errors with 4.0.0-beta.5

```
/Maui-Dev/CommonCode/XCGLogger/Sources/XCGLogger/Misc/HelperFunctions.swift:26:9: error: missing argument labels 'catch:finally:' in call
    _try(tryClosure, catchClosure, finallyClosure ?? {})
        ^
                     catch:        finally: 
/Maui-Dev/CommonCode/XCGLogger/Sources/XCGLogger/Misc/HelperFunctions.swift:35:12: error: missing argument label 'name:' in call
    _throw(NSException(name: NSExceptionName(rawValue: name), reason: message ?? name, userInfo: userInfo))
           ^
           name: 
```

**Comment by DaveWoodCom** [comment]
@neilt how are you building the project? There are a couple of Objective-C methods in the `XCGLogger.h` file, and it looks like they're not being included for you. You may need to add the `XCGLogger.h` to your bridging header file.

**Comment by DaveWoodCom** [comment]
I've released 4.0.0, first full release for Swift 3.0. Lots of new features making XCGLogger the most advanced, and still the best, debug logging framework for Swift.

If you use XCGLogger, it would be awesome if you'd help support it. You could buy my [Watchdog for Xcode](https://itunes.apple.com/us/app/watchdog-for-xcode/id734258109?mt=12&uo=4&at=11lMGu&pt=17255&ct=X) app, that you'll love just as much since it'll solve all kinds of problems for you (it looks after your DerivedData folder). At a minimum, please star the repo to show others you find it useful.

Buying Watchdog will help me get a new Mac. XCGLogger 4.0.0 was developed on an iMac with 20% of the screen non-functional. You have no idea how annoying it is when the right side of the monitor is dead. 😧

Anyway, hope you like the new version and can make use of the new features!

**Comment by marcusleon** [comment]
I notice after upgrading I am seeing a lot more log statements.  Ie: when making Alamofire request:

```
2016-10-08 18:04:56.788465 My App [86668:5107493] [] nw_socket_handle_socket_event Event mask: 0x2
2016-10-08 18:04:56.788841 My App[86668:5107493] [] nw_socket_handle_socket_event Socket received READ_CLOSE event
2016-10-08 18:04:56.789248 My App [86668:5107262] [] tcp_connection_event_notify 9 event: TCP_CONNECTION_EVENT_READ_CLOSE, reason: read closed, should 
```

Is there a reason for this?   And a way to suppress?

**Comment by PascalNsame** [comment]
Hello Dave,

I’m getting compiler errors with the new version of Swift. 
Details are attached.

Please advice if a fix is available.

Thanks
Pascal
![xcglogger_compiler_errors](https://cloud.githubusercontent.com/assets/23053392/19684641/670ebf12-9a86-11e6-88f3-e98500fa0133.png)

**Comment by DaveWoodCom** [comment]
@PascalNsame Not sure what you have set up incorrectly, but something is wrong. Those shouldn't be generating errors. I'd try clearing out your DerivedData and rebuilding. If you're still seeing errors, let me know what Xcode version/build you're using, and attach your podfile.

**Comment by PascalNsame** [comment]
Hello Dave,

I’m using the following Xcode version: Version 8.0 (8A218a)

After clean and rebuild. I still get the same errors. 

My podfile is attached.

Thanks
—
Pascal Nsame, President and CEO/CTO
Kardinal Microsystems, Inc. - 210 Colchester Ave., Burlington, VT 05405 USA - Phone: +1 802 489-7021 - Email:pascal.n@kardinal.co <mailto:pascal.n@kardinal.co>

**Comment by PascalNsame** [comment]
Hello Dave,

I get the same 18 Compiler Errors with latest Xcode Version 8.1 (8B62).

Please advice, if a fix is available, as I need to release a functioning product to my client tomorrow. 

Thanks
—
Pascal Nsame, President and CEO/CTO
Kardinal Microsystems, Inc. - 210 Colchester Ave., Burlington, VT 05405 USA - Phone: +1 802 489-7021 - Email:pascal.n@kardinal.co <mailto:pascal.n@kardinal.co>

**Comment by DaveWoodCom** [comment]
@PascalNsame I don't know why you're seeing those errors. I have lots of projects on the go using the latest XCGLogger and the latest Xcode (Version 8.1 (8B62)) and all are working fine. I'd try the usual stuff, delete DerivedData, do a pod update etc. It's definitely something to do with your set up.

If you want, I can take a look at your set up and help figure out the issue. I'm tempted to set up a Gitter or Slack room to help in cases like this. Let me know if you think it would be worth it for you.

Can email me directly here if you like: https://www.cerebralgardens.com/contact

**Comment by PascalNsame** [comment]
Hello Dave,

Can we do a Webex or Skype call this afternoon?
Please let me know what time works for you.

Thanks
—
Pascal Nsame, President and CEO/CTO
Kardinal Microsystems, Inc. - 210 Colchester Ave., Burlington, VT 05405 USA - Phone: +1 802 489-7021 - Email:pascal.n@kardinal.co <mailto:pascal.n@kardinal.co>

**Comment by DaveWoodCom** [comment]
@PascalNsame Sorry, it was Halloween, crazy busy. Email here tomorrow: https://www.cerebralgardens.com/contact and we can sort something out.
